---
- name: Установка Docker
  become: true
  block:
    - name: Добавляем Universe
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Установка дополнительных пакетов
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        update-cache: true
        cache_valid_time: 86400

    - name: Добавление директории /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Добавление ключа docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Установка стабильного репозитория репозитория
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update_cache: true
        filename: docker

    - name: Установка Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
        update_cache: true

    - name: Проверка, что docker установлен и перезагружен
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

- name: Установка Docker-compose
  become: true
  block:
    - name: Получение последней версии docker-compose
      ansible.builtin.uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: page
    - name: Установка Docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64
        dest: /usr/bin/docker-compose
        mode: "0755"
      register: out
- name: Проверка output установки docker-compose
  ansible.builtin.debug:
    var: out

- name: Настройка дополнительных пакетов python
  block:
    - name: Установка pip пакетов
      ansible.builtin.pip:
        name: docker

- name: Завершение установки
  become: true
  block:
    - name: Добавление пользователя в группу Docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        state: present
        groups: docker
        append: true
    - name: Перезагрузка сервера
      ansible.builtin.reboot:
        msg: Rebooting...
